# Generated by Django 4.0.4 on 2022-05-20 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import restaurants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id_restaurant', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_representative', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del representante')),
                ('last_name_representative', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido del representante')),
                ('phone_number', models.CharField(max_length=10, null=True, verbose_name='Número de teléfono del restaurante')),
                ('phone_number_representative', models.CharField(max_length=10, null=True, verbose_name='Número de teléfono del representante')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Dirección')),
                ('neighborhood', models.CharField(max_length=100, null=True, verbose_name='Barrio')),
                ('description', models.CharField(max_length=254, null=True, verbose_name='Descripción')),
                ('menu', models.FileField(blank=True, null=True, upload_to=restaurants.models.Restaurant.nameFile, verbose_name='Menú')),
                ('prices', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Precios')),
                ('schedule', models.CharField(blank=True, max_length=20, null=True, verbose_name='Horario de atención')),
                ('active', models.BooleanField(default=False, verbose_name='Activo')),
                ('type_food', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de comida')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
            },
        ),
        migrations.CreateModel(
            name='TagsRestaurant',
            fields=[
                ('id_tags', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tags', models.CharField(blank=True, max_length=254, null=True, verbose_name='Tag')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='GalleryRestaurant',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=restaurants.models.GalleryRestaurant.nameImage)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Galería',
                'verbose_name_plural': 'Galerías',
            },
        ),
    ]
