# Generated by Django 4.0.4 on 2022-06-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='environment',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Ambiente'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vegetarian',
            field=models.BooleanField(default=False, verbose_name='Vegetariano'),
        ),
    ]
