# Generated by Django 4.0.4 on 2022-06-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_environment_restaurant_vegetarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='schedule',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Horario de atención'),
        ),
    ]
