# Generated by Django 4.0.4 on 2022-06-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='new',
            field=models.BooleanField(default=False, verbose_name='Nuevo'),
        ),
    ]
