# Generated by Django 4.0.4 on 2022-06-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='punctuation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Puntuación'),
        ),
    ]
