# Generated by Django 4.0.4 on 2022-06-29 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_punctuation'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 29, 20, 2, 58, 258713), verbose_name='Fecha'),
        ),
    ]
