# Generated by Django 4.0.4 on 2022-06-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
