# Generated by Django 4.0.4 on 2022-10-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_alter_restaurant_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
