# Generated by Django 4.0.4 on 2022-10-25 22:34

from django.db import migrations, models
import django.db.models.deletion
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_alter_restaurant_id_restaurant_alter_restaurant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryrestaurant',
            name='id_imagen',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID Imagen'),
        ),
        migrations.AlterField(
            model_name='galleryrestaurant',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=restaurants.models.GalleryRestaurant.nameImage, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='galleryrestaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='restaurants.restaurant', verbose_name='ID Restaurante'),
        ),
    ]
