# Generated by Django 4.0.4 on 2022-10-25 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_alter_galleryrestaurant_id_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryrestaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='restaurants.restaurant', verbose_name='ID RESTAURANTE'),
        ),
    ]
