# Generated by Django 4.0.4 on 2022-10-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_alter_galleryrestaurant_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsrestaurant',
            name='id_tags',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID Etiqueta'),
        ),
        migrations.AlterField(
            model_name='tagsrestaurant',
            name='tags',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Etiqueta'),
        ),
    ]
