# Generated by Django 4.0.4 on 2022-11-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_alter_tagsrestaurant_id_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='punctuation',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Puntuación'),
        ),
    ]
