# Generated by Django 4.0.4 on 2022-10-19 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_restaurant_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Sugerencias')),
                ('id_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_comments', to='restaurants.restaurant')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
