# Generated by Django 4.0.4 on 2022-10-19 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_commensal_environment_commensal_interest_and_more'),
        ('suggestions', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commensal_comments', to='users.commensal'),
        ),
        migrations.AlterField(
            model_name='score',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commensal', to='users.commensal'),
        ),
    ]
