# Generated by Django 4.0.4 on 2022-10-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0003_alter_comments_id_user_alter_score_id_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
    ]
