# Generated by Django 4.0.4 on 2022-10-20 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_restaurant_date'),
        ('users', '0002_commensal_environment_commensal_interest_and_more'),
        ('suggestions', '0004_alter_comments_options_alter_score_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='id_restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='restaurants.restaurant', verbose_name='Restaurante'),
        ),
        migrations.AlterField(
            model_name='score',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commensal', to='users.commensal', verbose_name='Comensal'),
        ),
    ]
