# Generated by Django 4.0.4 on 2022-10-20 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_commensal_environment_commensal_interest_and_more'),
        ('restaurants', '0008_alter_restaurant_date'),
        ('suggestions', '0005_alter_score_id_restaurant_alter_score_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(verbose_name='Sugerencias'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='id_restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_comments', to='restaurants.restaurant', verbose_name='Restaurante'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commensal_comments', to='users.commensal', verbose_name='Comensal'),
        ),
    ]
