# Generated by Django 4.0.4 on 2022-10-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0006_alter_comments_comment_alter_comments_id_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios'),
        ),
    ]
