# Generated by Django 4.0.4 on 2022-10-20 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0008_alter_restaurant_date'),
        ('suggestions', '0007_score_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id_restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commentsid_restaurant', to='restaurants.restaurant', verbose_name='Restaurante'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commentsid_user', to=settings.AUTH_USER_MODEL, verbose_name='Comensal'),
        ),
        migrations.AlterField(
            model_name='score',
            name='id_restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Scoreid_restaurant', to='restaurants.restaurant', verbose_name='Restaurante'),
        ),
        migrations.AlterField(
            model_name='score',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Scoreid_user', to=settings.AUTH_USER_MODEL, verbose_name='Comensal'),
        ),
    ]
