# Generated by Django 4.0.4 on 2022-10-25 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0008_alter_comments_id_restaurant_alter_comments_id_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
    ]
