# Generated by Django 4.0.4 on 2022-10-31 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0017_alter_tagsrestaurant_id_tags_and_more'),
        ('suggestions', '0010_comments_date_alter_score_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False, verbose_name='Favorito')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('id_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_restaurant', to='restaurants.restaurant', verbose_name='Restaurante')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user', to=settings.AUTH_USER_MODEL, verbose_name='Comensal')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
            },
        ),
    ]
