# Generated by Django 4.0.4 on 2022-06-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commensal',
            name='environment',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Ambiente'),
        ),
        migrations.AddField(
            model_name='commensal',
            name='interest',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Interés'),
        ),
        migrations.AddField(
            model_name='commensal',
            name='vegetarian',
            field=models.BooleanField(default=False, verbose_name='Vegetariano'),
        ),
    ]
